version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - API_KEY=${API_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - COINGECKO_API_URL=${COINGECKO_API_URL}
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
